### ISSUE TITLE
401 Error when trying to sync

### ISSUE THREAD

**Issue by joshuagrimes** [AAndyProgram/PlexEmbySync#5]
When trying to sync, I'm getting a success message, but nothing is synced. It looks like the issue is on the plex side.

Error log entry:
```
2022-12-24 13:19:08: API.Plex.Functions.GetUserItemsList
	The remote server returned an error: (401) Unauthorized.
2022-12-24 13:19:08: Message: The remote server returned an error: (401) Unauthorized.
	HelpLink: 
	StackTrace:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
	   at System.Net.WebClient.DownloadString(Uri address)
	   at PlexEmbySync.API.Plex.Functions.GetUserItemsList(Library _Library, UserData _User, Boolean UsingTasks, CancellationToken Token)
```

**Comment by AAndyProgram** [comment]
I guess something is missing (token?).
https://github.com/AAndyProgram/PlexEmbySync#setup-plex
